[build]
    command = "npm run build"
    publish = "www/public"

[build.environment]
    HUGO_VERSION = "0.31.1"

[context.production.environment]
    HUGO_ENV = "production"
    NODE_ENV = "production"

[context.deploy-preview]
    command = "npm run build:preview"